# Training configuration for multi-label car classification

# Data settings
data:
  json_path: "project-1-at-2025-10-05-21-43-98b8ac33.json"
  image_dir: "images"  # Update this path to your image directory
  val_split: 0.2
  image_size: 224
  batch_size: 32
  num_workers: 4

# Model settings
model:
  backbone: "resnet50"  # Options: resnet50, efficientnet_b0, densenet121, etc.
  pretrained: true
  dropout_rate: 0.5

# Training settings
training:
  epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler_step: 10
  scheduler_gamma: 0.1
  early_stopping_patience: 10

# Output settings
output:
  save_dir: "checkpoints"
  save_best: true
  log_interval: 10

# Other settings
misc:
  seed: 42
  device: "auto"  # auto, cpu, cuda
  freeze_backbone: false
