version: '3.8'

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=password
      - POSTGRE_HOST=db
      - POSTGRE_PORT=5432
      - LABEL_STUDIO_HOST=http://localhost:8080
    volumes:
      - label-studio-data:/label-studio/data
    depends_on:
      - db
    networks:
      - label-studio-network

  db:
    image: postgres:13
    container_name: label-studio-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - label-studio-network

volumes:
  label-studio-data:
  postgres-data:

networks:
  label-studio-network:
    driver: bridge